-- MySQL Script generated by MySQL Workbench
-- Thu Apr  7 13:36:42 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `bio` VARCHAR(45) NULL,
  `picture` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `industry` VARCHAR(45) NULL,
  `LD_num` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`LD_num`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Business` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Business` (
  `company_name` VARCHAR(45) NOT NULL,
  `industry` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `contact_email` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`company_name`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Message` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Message` (
  `*msgLd_num` INT NOT NULL,
  `SendTimeStamp` VARCHAR(45) NULL,
  `Sender Ld_num` VARCHAR(45) NULL,
  `Reciever Ld_num` VARCHAR(45) NULL,
  `Reciever TimeStamp` VARCHAR(45) NULL,
  `contents` VARCHAR(45) NULL,
  PRIMARY KEY (`*msgLd_num`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Experience` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Experience` (
  `id` VARCHAR(45) NOT NULL,
  `data_start` DATETIME NULL,
  `data_end` DATETIME NULL,
  `title` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `User_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Experience_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Publication` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Publication` (
  `title` VARCHAR(45) NOT NULL,
  `date` DATETIME NULL,
  `description` VARCHAR(45) NULL,
  `authors` VARCHAR(45) NOT NULL,
  `User_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`title`, `authors`, `User_email`),
  CONSTRAINT `fk_Publication_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Education` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Education` (
  `type` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `school` VARCHAR(45) NULL,
  `User_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type`),
  CONSTRAINT `fk_Education_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skill` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `skill` (
  `name` VARCHAR(45) NOT NULL,
  `User_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `fk_skill_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Language` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Language` (
  `name` VARCHAR(45) NOT NULL,
  `User_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `fk_Language_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Organization` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Organization` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `date_start` DATETIME NULL,
  `data_end` DATETIME NULL,
  `User_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Organization_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Business_has_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Business_has_User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Business_has_User` (
  `Business_company_name` VARCHAR(45) NOT NULL,
  `User_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Business_company_name`, `User_email`),
  CONSTRAINT `fk_Business_has_User_Business1`
    FOREIGN KEY (`Business_company_name`)
    REFERENCES `Business` (`company_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Business_has_User_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User_has_Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User_has_Message` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User_has_Message` (
  `User_LD_num` VARCHAR(25) NOT NULL,
  `Message_*msgLd_num` INT NOT NULL,
  PRIMARY KEY (`User_LD_num`, `Message_*msgLd_num`),
  CONSTRAINT `fk_User_has_Message_User1`
    FOREIGN KEY (`User_LD_num`)
    REFERENCES `User` (`LD_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Message_Message1`
    FOREIGN KEY (`Message_*msgLd_num`)
    REFERENCES `Message` (`*msgLd_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
